import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/custom/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { prisma } from "@/lib/db";
import { currentUser } from "@clerk/nextjs/server";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MarvelSass",
  description: "Generated by create next app",
};

async function getData(userId: string) {
  if (userId) {
    const data = await prisma.user.findUnique({
      where: {
        id: userId,
      },
      select: {
        colorScheme: true,
      },
    });

    return data;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  const data = user?.id ? await getData(user.id) : null;
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className} ${
            data?.colorScheme ?? `theme-orange`
          }`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
